services:
  - type: web
    name: laravel-blog
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan migrate --force || true
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: your-db-name
          property: host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        fromDatabase:
          name: your-db-name
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: your-db-name
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: your-db-name
          property: password
